### ISSUE TITLE
Translations for AoC

### ISSUE THREAD

**Issue by ar1ja** [topaz/aoc-tmp-stats#1]
hello Eric,

first up, im srry for making an issue here, you dont have an email
listed anywhere and i dont have a twitter account, this is my only means
of communication with you

with that out of the way, dont you think translations for advent of code
would be a nice idea ? i mean im lithuanian and am fine in english but would
be cool for people who dont speak english or just want aoc in their native language

anyway, hope to hear from you, thanks for reading this if you do lol

**Comment by topaz** [comment]
Hi! This is not the appropriate place to contact me.  Please see: http://was.tl/contact/

**Comment by ar1ja** [comment]
> Hi! This is not the appropriate place to contact me. Please see: http://was.tl/contact/

thanks
